/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-on-surface": "#313030",
        "secondary": "#c8c6c5",
        "secondary-fixed": "#e5e2e1",
        "surface-dim": "#000000",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-error": "#690005",
        "on-primary": "#2f3131",
        "primary-container": "#e2e2e2",
        "surface-variant": "#353434",
        "primary": "#ffffff",
        "surface-tint": "#c6c6c7",
        "tertiary-fixed": "#d3e4fe",
        "on-background": "#e5e2e1",
        "error": "#ffb4ab",
        "on-tertiary-container": "#56657c",
        "surface-container-highest": "#353434",
        "on-secondary": "#313030",
        "secondary-container": "#4a4949",
        "background": "#000000",
        "tertiary": "#ffffff",
        "outline": "#8e9192",
        "on-secondary-container": "#bab8b7",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#454747",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary": "#213145",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#474646",
        "tertiary-container": "#d3e4fe",
        "surface-container-low": "#1c1b1b",
        "primary-fixed": "#e2e2e2",
        "outline-variant": "#444748",
        "on-surface-variant": "#c4c7c8",
        "on-primary-container": "#636565",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "surface": "#000000",
        "primary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-primary": "#5d5f5f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "32px",
        "unit": "8px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "margin-mobile": "24px",
        "section-gap": "160px",
        "unit-2": "16px",
        "unit-3": "24px",
        "unit-4": "32px",
        "unit-6": "48px",
        "unit-8": "64px",
        "unit-12": "96px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["80px", {"lineHeight": "96px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}]
      },
      animation: {
        'marquee': 'marquee 25s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        }
      }
    },
  },
  plugins: [],
}
